// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pryvjisdevbgqmfiuhwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByeXZqaXNkZXZiZ3FtZml1aHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTUxNTAsImV4cCI6MjA2MDgzMTE1MH0.1ys9MSzaMt48TRWKt0fIeksDOT_D-_YpA1qjnYGveuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);